[program:mesukdome-line-worker]
directory=/var/www/mesukdome
command=/usr/bin/php artisan queue:work line-redis --queue=line --tries=3 --sleep=1 --timeout=120 --max-time=3600
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/mesukdome-line-worker.log
stopwaitsecs=3600
environment=APP_ENV="production",APP_DEBUG="false"