[program:mesukdome-scheduler]
directory=/var/www/mesukdome
command=/usr/bin/php artisan schedule:work
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/mesukdome-scheduler.log
stopwaitsecs=3600
environment=APP_ENV="production",APP_DEBUG="false"